name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y clang clang-tidy smatch coccinelle libcmocka-dev
      - name: Format
        run: clang-format --dry-run --Werror $(git ls-files '*.c' '*.h')
      - name: Static analysis
        run: clang-tidy $(git ls-files '*.c') -- -Iinclude -Itest -Itest/bpf
      - name: Build
        run: gcc -std=c11 -Wall -Wextra -Itest -Itest/bpf -Iinclude test/test_xdp.c -o test/test_xdp $(pkg-config --libs cmocka)
      - name: Run tests
        run: ./test/test_xdp
